### PR TITLE
Added reference to Tisane

### PR DESCRIPTION
**Pull request by vadim-berman**
Tisane is an API / SDK honed for legal applications and detection of abusive content.

### CODE REVIEW

**Comment by bwaltl** [comment]
It seems as if Tisane is a commercial and proprietary product. This repository is intended to share only non-proprietary resources.

**Comment by vadim-berman** [comment]
Thanks, @bwaltl. Technically, spaCy is proprietary as well, just free. 

But yes indeed, Tisane is proprietary. There is a free plan though, not restricted in time. Does that count?

**Comment by bwaltl** [comment]
I see. At least spacy offers more insights via [Github](https://github.com/explosion/spaCy). Does the same argument apply to Tisane as well? I was not able to find anything that is shared at Github (or some other platform).

I would suggest that we should avoid incorporating solutions that are primarily proprietary and don't offer some code / resource / data / annotations / etc. that can be reused. Otherwise we would end up with a list of commercial vendors / start-ups, etc. There are lots of those out there already.

**Comment by vadim-berman** [comment]
In terms of source code? No, just the scripts, the documentation, etc. 

I guess "it is what it is". If it doesn't work, then I guess we don't fit. 

But I can tell you for sure that there are not many proprietary libraries with NLP honed to legal tech. I mean, there are those with regexes fore credit cards, and the generic ones, plus a couple that detect toxicity, but so far I have seen none that extract attempts to organise criminal activities, etc. 

But if no, then no, of course. Thanks for your consideration.

**Pull request closed without merging**
